[settings]
uri = "mongodb://127.0.0.1:27017"
db = "crystal"
collection = "posts"
number_threads = "max"
number_documents = 1_000_000
batch_size = 10_000
time_step_ms = 20

[document_fields]
complex_string = {function = "generate_long_string", length = 100}
text = "example" 
created_at = "custom_created_at"
updated_at = "custom_updated_at"